---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-customer1
  labels:
    tenant: customer1
    isolation: strict
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-customer2
  labels:
    tenant: customer2
    isolation: strict
---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-customer3
  labels:
    tenant: customer3
    isolation: strict
